# Generated by Django 5.0.6 on 2024-07-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_genre_alter_user_certifs_certif_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acertif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('genre', models.ManyToManyField(blank=True, related_name='acertifs', to='base.genre')),
                ('who', models.ForeignKey(on_delete=models.SET('Unknown Who'), to='base.who')),
            ],
        ),
    ]
