# Generated by Django 5.0.6 on 2024-07-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_acertif'),
    ]

    operations = [
        migrations.AddField(
            model_name='certif',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certif',
            name='name',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Acertif',
        ),
    ]
